export const MOCK_LEADS_DATA = [
  {
    "fullName": "steve morris",
    "firstName": "steve",
    "lastName": "morris",
    "jobTitle": "chief executive officer of i'm g clothing",
    "companyName": "zazzle",
    "companyWebsite": "zazzle.com",
    "companyIndustry": "software development",
    "companySize": "201-500",
    "companyLocation": "redwood city, california, united states",
    "companyLocality": "redwood city",
    "companyRegion": "california",
    "companyCountry": "united states",
    "companyLinkedin": "linkedin.com/company/zazzle",
    "personRegion": true,
    "personCountry": "united states",
    "personLocality": true,
    "twitterUrl": "twitter.com/imgclothing",
    "twitterHandle": "imgclothing",
    "facebookUrl": "facebook.com/imgclothing",
    "linkedinPersonal": "linkedin.com/in/imgclothing",
    "linkedinUsername": "imgclothing",
    "workEmailAvailable": true,
    "personalEmailAvailable": true,
    "mobilePhoneAvailable": true,
    "seniorityLevels": [
      "cxo"
    ],
    "skills": [
      "advertising", "apparel", "brand development", "computer graphics",
      "consumer internet", "creative marketer", "digital marketing", "digital photography",
      "e commerce", "entrepreneur", "entrepreneurship", "fashion design",
      "graphic arts", "graphic design", "marketing", "networking", "online marketing",
      "product development", "promotions", "retail", "sales", "self driven",
      "self starter", "selling skills", "small business", "social media",
      "social media marketing", "social networking", "start ups", "usability design",
      "user experience", "user interface design", "ux research", "video editing",
      "video production", "web design"
    ],
    "interests": [
      "art", "barack obama", "britney spears", "brown university",
      "business management", "coldplay (band)", "collecting", "cooking",
      "crafts", "electronics", "eminem", "fashion/design", "gourmet cooking",
      "home decoration", "home improvement", "india", "jazz music", "kate moss",
      "katy perry", "lady gaga", "music", "new york yankees", "reading", "sports",
      "sustainable technology", "suze orman", "the new york times", "tiger woods",
      "twitter", "web design", "youtube"
    ],
    "personIndustry": "retail",
    "seniorityLabel": "cxo",
    "jobTenureStart": "2009-06",
    "companyFounded": 1999,
    "companyMetro": "san francisco, california",
    "githubUrl": ""
  },
  {
    "fullName": "susan hailey",
    "firstName": "susan",
    "lastName": "hailey",
    "jobTitle": "chief human resource officer",
    "companyName": "enable",
    "companyWebsite": "enable.com",
    "companyIndustry": "software development",
    "companySize": "501-1000",
    "companyLocation": "san francisco, california, united states",
    "companyLocality": "san francisco",
    "companyRegion": "california",
    "companyCountry": "united states",
    "companyLinkedin": "linkedin.com/company/enable-software",
    "personRegion": true,
    "personCountry": "united states",
    "personLocality": true,
    "twitterUrl": "twitter.com/susanhailey",
    "twitterHandle": "susanhailey",
    "facebookUrl": "facebook.com/susanlyonhailey",
    "linkedinPersonal": "linkedin.com/in/susanlyonhailey",
    "linkedinUsername": "susanlyonhailey",
    "workEmailAvailable": true,
    "personalEmailAvailable": true,
    "mobilePhoneAvailable": true,
    "seniorityLevels": [
      "cxo"
    ],
    "skills": [
      "analytics", "applicant tracking systems", "business development", "business strategy",
      "business turn arounds", "career development", "cloud computing", "competitive analysis",
      "consulting", "crm", "cross functional team leadership", "e commerce",
      "e recruitment", "employee engagement", "employer branding", "enterprise software",
      "entrepreneurship", "executive coaching", "executive leadership", "executive management",
      "executive search", "fundraising", "global talent acquisition", "growth strategies",
      "hiring", "hr consulting", "hris", "human capital management", "human resources",
      "human resources information systems", "leadership", "leadership development",
      "management", "management consulting", "mergers and acquisitions", "mobile devices",
      "networking", "non profit management", "organizational development", "organizational leadership",
      "product design", "professional services", "program management", "recruiting",
      "saas", "sales", "scalability", "search", "software as a service", "sourcing",
      "start ups", "strategic hiring", "strategic human resource planning", "strategic partnerships",
      "strategic planning", "strategy", "succession planning", "talent acquisition",
      "talent management", "talent mapping", "team building", "team leadership", "vendor management"
    ],
    "interests": [
      "arts and culture", "economic empowerment", "education", "human rights", "science and technology"
    ],
    "personIndustry": "computer software",
    "seniorityLabel": "cxo",
    "jobTenureStart": "2024-09",
    "companyFounded": 2016,
    "companyMetro": "san francisco, california",
    "githubUrl": ""
  },
  {
    "fullName": "tom thimot",
    "firstName": "tom",
    "lastName": "thimot",
    "jobTitle": "chief executive officer",
    "companyName": "rova",
    "companyWebsite": "rova.com",
    "companyIndustry": "software development",
    "companySize": "11-50",
    "companyLocation": "new york, new york, united states",
    "companyLocality": "new york",
    "companyRegion": "new york",
    "companyCountry": "united states",
    "companyLinkedin": "linkedin.com/company/rova",
    "personRegion": true,
    "personCountry": "united states",
    "personLocality": true,
    "twitterUrl": "twitter.com/thimot",
    "twitterHandle": "thimot",
    "facebookUrl": "facebook.com/tom.thimot",
    "linkedinPersonal": "linkedin.com/in/tom-thimot-988308",
    "linkedinUsername": "tom-thimot-988308",
    "workEmailAvailable": true,
    "personalEmailAvailable": true,
    "mobilePhoneAvailable": true,
    "seniorityLevels": [
      "cxo"
    ],
    "skills": [
      "analytics", "big data", "business alliances", "business development",
      "business planning", "business process", "cloud computing", "competitive analysis",
      "consulting", "corporate venture capital", "crm", "cross functional team leadership",
      "customer relationship management", "data center", "e commerce", "enterprise software",
      "entrepreneurship", "executive management", "fundraising", "go to market strategy",
      "integrated marketing", "it strategy", "leadership", "managed services",
      "management", "mergers", "mergers and acquisitions", "mobile applications",
      "new business development", "product development", "product management",
      "product marketing", "professional services", "program management", "saas",
      "sales", "sales management", "sales operations", "sales process", "salesforce.com",
      "social commerce", "social media", "software as a service", "start ups",
      "strategic partnerships", "strategic planning", "strategy", "technology incubation",
      "telecommunications", "venture capital"
    ],
    "interests": [
      "children", "collecting", "education", "kids", "my three daughters", "sailing",
      "scuba diving", "skiing", "travel"
    ],
    "personIndustry": "computer software",
    "seniorityLabel": "cxo",
    "jobTenureStart": "2025-08",
    "companyFounded": 1995,
    "companyMetro": "new york, new york",
    "githubUrl": ""
  },
  {
    "fullName": "erick herring",
    "firstName": "erick",
    "lastName": "herring",
    "jobTitle": "chief technology officer",
    "companyName": "vynyl",
    "companyWebsite": "vynyl.com",
    "companyIndustry": "software development",
    "companySize": "11-50",
    "companyLocation": "los angeles, california, united states",
    "companyLocality": "los angeles",
    "companyRegion": "california",
    "companyCountry": "united states",
    "companyLinkedin": "linkedin.com/company/vynyl",
    "personRegion": true,
    "personCountry": "united states",
    "personLocality": true,
    "twitterUrl": "twitter.com/erickherring",
    "twitterHandle": "erickherring",
    "facebookUrl": "facebook.com/erick.herring",
    "linkedinPersonal": "linkedin.com/in/erickherring",
    "linkedinUsername": "erickherring",
    "workEmailAvailable": true,
    "personalEmailAvailable": true,
    "mobilePhoneAvailable": true,
    "seniorityLevels": [
      "cxo"
    ],
    "skills": [
      "agile methodologies", "agile project management", "amazon web services", "analytics",
      "architecture", "architectures", "big data", "business intelligence",
      "business strategy", "cissp", "cloud computing", "data center", "digital marketing",
      "distributed systems", "e commerce", "enterprise software", "entrepreneurship",
      "executive management", "fast healthcare interoperability resources",
      "healthcare information technology", "information security", "it management",
      "it operations", "it strategy", "leadership", "management", "metrics",
      "mobile applications", "mobile devices", "network architecture", "networking",
      "online advertising", "physical security", "ppc", "product development",
      "product management", "product strategy", "program management", "project management",
      "recruiting", "saas", "scalability", "security", "sem", "soa", "software development",
      "start ups", "strategic partnerships", "strategy", "technical architecture",
      "web analytics", "web applications"
    ],
    "interests": [
      "animal welfare", "arts and culture", "austin", "book recommendations",
      "business strategy", "cooking", "copenhagen", "denmark", "electronics",
      "facebook platform", "game theory", "groupon", "health", "home decoration",
      "home improvement", "itunes", "lean startups", "los angeles", "pasadena",
      "pizza", "reading", "science and technology", "screenwriting", "social games",
      "viral growth and analytics", "writing"
    ],
    "personIndustry": "higher education",
    "seniorityLabel": "cxo",
    "jobTenureStart": "2014-10",
    "companyFounded": 2013,
    "companyMetro": "los angeles, california",
    "githubUrl": "github.com/erick"
  },
  {
    "fullName": "lucas rotter",
    "firstName": "lucas",
    "lastName": "rotter",
    "jobTitle": "chief executive officer & co-founder",
    "companyName": "valcre®",
    "companyWebsite": "valcre.com",
    "companyIndustry": "software development",
    "companySize": "51-200",
    "companyLocation": "la jolla, california, united states",
    "companyLocality": "la jolla",
    "companyRegion": "california",
    "companyCountry": "united states",
    "companyLinkedin": "linkedin.com/company/valcre",
    "personRegion": true,
    "personCountry": "united states",
    "personLocality": true,
    "twitterUrl": "twitter.com/lucasrotter",
    "twitterHandle": "lucasrotter",
    "facebookUrl": "facebook.com/lucas.rotter",
    "linkedinPersonal": "linkedin.com/in/lucasrotter",
    "linkedinUsername": "lucasrotter",
    "workEmailAvailable": true,
    "personalEmailAvailable": true,
    "mobilePhoneAvailable": true,
    "seniorityLevels": [
      "cxo", "owner"
    ],
    "skills": [
      "analysis", "appraisals", "argus modeling", "asset management", "brand development",
      "brokerage", "budgets", "business analysis", "business consulting",
      "business requirements", "business strategy", "change management",
      "commercial real estate", "competitive analysis", "corporate branding",
      "due diligence", "emotional intelligence", "enterprise software", "excel",
      "executive management", "financial analysis", "financial modeling",
      "leadership", "leases", "management", "market analysis", "marketing",
      "marketing strategy", "microsoft excel", "microsoft office", "microsoft word",
      "portfolio management", "powerpoint", "program management", "project management",
      "real estate", "retail", "sdlc", "social media marketing", "software development",
      "software implementation", "stakeholder engagement", "strategic planning",
      "strategy", "strategy development", "technology development", "technology planning",
      "technology solution development", "valuation", "vba", "word"
    ],
    "interests": [
      "advertisement design", "advertising", "apple", "blogging", "coffee",
      "college football", "computers", "cooking", "golf", "investing", "learning",
      "photography", "technology", "web editing", "writing"
    ],
    "personIndustry": "computer hardware",
    "seniorityLabel": "cxo",
    "jobTenureStart": "2016-08",
    "companyFounded": 2016,
    "companyMetro": "san diego, california",
    "githubUrl": ""
  },
  {
    "fullName": "kunal datta",
    "firstName": "kunal",
    "lastName": "datta",
    "jobTitle": "chief product officer",
    "companyName": "unit21",
    "companyWebsite": "unit21.ai",
    "companyIndustry": "software development",
    "companySize": "51-200",
    "companyLocation": "san francisco, california, united states",
    "companyLocality": "san francisco",
    "companyRegion": "california",
    "companyCountry": "united states",
    "companyLinkedin": "linkedin.com/company/unit21",
    "personRegion": true,
    "personCountry": "united states",
    "personLocality": true,
    "twitterUrl": "",
    "twitterHandle": "",
    "facebookUrl": "facebook.com/datta.kunal",
    "linkedinPersonal": "linkedin.com/in/kunal-datta",
    "linkedinUsername": "kunal-datta",
    "workEmailAvailable": true,
    "personalEmailAvailable": true,
    "mobilePhoneAvailable": true,
    "seniorityLevels": [
      "cxo"
    ],
    "skills": [
      "agile methodologies", "analysis", "artificial intelligence", "business development",
      "chuck", "design thinking", "entrepreneurship", "java", "leadership",
      "management", "market research", "marketing", "matlab", "microsoft excel",
      "microsoft office", "multi instrumentalist", "music", "new product ideas",
      "pagemaker", "powerpoint", "product leadership", "product management",
      "product vision", "public speaking", "research", "scaled agile framework",
      "scrum", "sketchup", "social media", "start ups", "storytelling", "strategy",
      "teaching", "user centered design", "user experience"
    ],
    "interests": [
      "arts and culture", "civil rights and social action", "economic empowerment",
      "education", "environment", "politics", "poverty alleviation", "science and technology"
    ],
    "personIndustry": "computer hardware",
    "seniorityLabel": "cxo",
    "jobTenureStart": "2026-02",
    "companyFounded": 2018,
    "companyMetro": "san francisco, california",
    "githubUrl": ""
  },
  {
    "fullName": "clint parker",
    "firstName": "clint",
    "lastName": "parker",
    "jobTitle": "chief technology officer",
    "companyName": "simpro software",
    "companyWebsite": "simprogroup.com",
    "companyIndustry": "software development",
    "companySize": "501-1000",
    "companyLocation": "miami, florida, united states",
    "companyLocality": "miami",
    "companyRegion": "florida",
    "companyCountry": "united states",
    "companyLinkedin": "linkedin.com/company/simpro-software",
    "personRegion": true,
    "personCountry": "united states",
    "personLocality": true,
    "twitterUrl": "twitter.com/clintcparker",
    "twitterHandle": "clintcparker",
    "facebookUrl": "facebook.com/clintcparker",
    "linkedinPersonal": "linkedin.com/in/clintcparker",
    "linkedinUsername": "clintcparker",
    "workEmailAvailable": true,
    "personalEmailAvailable": true,
    "mobilePhoneAvailable": true,
    "seniorityLevels": [
      "cxo"
    ],
    "skills": [
      ".net framework", "agile methodologies", "api development", "architecture",
      "asp.net", "asp.net core", "asp.net mvc", "c#", "cloud computing", "coaching",
      "continuous delivery", "continuous integration",
      "continuous integration and continuous delivery", "css", "databases", "devops",
      "enterprise software", "html", "integration", "javascript", "jquery", "json",
      "kubernetes", "leadership", "linux", "management", "mentoring", "microservices",
      "microsoft sql server", "mobile applications", "object oriented programming",
      "problem solving", "representational state transfer", "requirements analysis",
      "saas", "scrum", "service oriented architecture design", "soa",
      "software as a service", "software design", "software development",
      "software development life cycle", "software industry", "software project management",
      "software quality assurance", "sonarqube", "sql", "system architecture",
      "team leadership", "test automation", "vbscript", "web development", "web services"
    ],
    "interests": [
      "animal welfare", "children", "civil rights and social action", "couchdb",
      "education", "email addresses", "environment", "health", "human rights",
      "javascript", "node", "poverty alleviation", "rfcs", "science and technology",
      "web development", "web standards"
    ],
    "personIndustry": "computer software",
    "seniorityLabel": "cxo",
    "jobTenureStart": "2025-12",
    "companyFounded": 2002,
    "companyMetro": "miami, florida",
    "githubUrl": "github.com/clintcparker"
  },
  {
    "fullName": "joseph farrell",
    "firstName": "joseph",
    "lastName": "farrell",
    "jobTitle": "chief product officer",
    "companyName": "alethium health systems",
    "companyWebsite": "alethium.health",
    "companyIndustry": "software development",
    "companySize": "11-50",
    "companyLocation": "west hollywood, california, united states",
    "companyLocality": "west hollywood",
    "companyRegion": "california",
    "companyCountry": "united states",
    "companyLinkedin": "linkedin.com/company/alethium-health-systems",
    "personRegion": true,
    "personCountry": "united states",
    "personLocality": true,
    "twitterUrl": "twitter.com/josephefarrell",
    "twitterHandle": "josephefarrell",
    "facebookUrl": "facebook.com/joe.farrell.3538",
    "linkedinPersonal": "linkedin.com/in/josephefarrell",
    "linkedinUsername": "josephefarrell",
    "workEmailAvailable": true,
    "personalEmailAvailable": true,
    "mobilePhoneAvailable": true,
    "seniorityLevels": [
      "cxo"
    ],
    "skills": [
      "advertising", "agile methodologies", "analytics", "brand development",
      "business development", "business intelligence", "certified project manager",
      "client development", "consulting", "content strategy", "copywriting",
      "creative direction", "creative strategy", "crm", "digital marketing",
      "digital media", "digital strategy", "e commerce", "email marketing",
      "information architecture", "integrated marketing", "interactive advertising",
      "interactive marketing", "leadership", "management", "marketing",
      "marketing strategy", "mobile applications", "mobile devices", "mobile marketing",
      "mobile technology", "online advertising", "online marketing", "pmp",
      "product management", "program management", "project management", "scrum",
      "sdlc", "seo", "social media", "social media marketing", "strategic partnerships",
      "strategic planning", "strategy", "technology commercialization", "user experience",
      "user interface design", "vendor management", "web analytics",
      "web project management"
    ],
    "interests": [
      "1984", "brave new world", "classic cinema", "classic cinema and skiing",
      "film noir", "notes on a scandal", "photography", "reading (poetry and fiction)",
      "richard iii", "skiing", "some of my favorite books/ plays are",
      "some of my favorite books/plays are", "the butter battle book",
      "the dark knight returns", "the zoo story"
    ],
    "personIndustry": "computer software",
    "seniorityLabel": "cxo",
    "jobTenureStart": "2021-11",
    "companyFounded": 2019,
    "companyMetro": "los angeles, california",
    "githubUrl": ""
  },
  {
    "fullName": "chris ernst",
    "firstName": "chris",
    "lastName": "ernst",
    "jobTitle": "chief learning officer",
    "companyName": "workday",
    "companyWebsite": "workday.com",
    "companyIndustry": "software development",
    "companySize": "10001+",
    "companyLocation": "pleasanton, california, united states",
    "companyLocality": "pleasanton",
    "companyRegion": "california",
    "companyCountry": "united states",
    "companyLinkedin": "linkedin.com/company/workday",
    "personRegion": true,
    "personCountry": "united states",
    "personLocality": true,
    "twitterUrl": "twitter.com/cternst",
    "twitterHandle": "cternst",
    "facebookUrl": "facebook.com/chris.ernst.507",
    "linkedinPersonal": "linkedin.com/in/chrisernstpaloalto",
    "linkedinUsername": "chrisernstpaloalto",
    "workEmailAvailable": true,
    "personalEmailAvailable": true,
    "mobilePhoneAvailable": true,
    "seniorityLevels": [
      "cxo"
    ],
    "skills": [
      "360 feedback", "account management", "automation", "board level",
      "business strategy", "career development", "career management", "change management",
      "coaching", "conflict resolution", "consulting", "continuous improvement",
      "cross cultural", "cross functional collaborations", "cross functional team leadership",
      "culture change", "employee training", "executive coaching", "executive development",
      "executive management", "fluid power", "globalization", "hr consulting",
      "human capital", "human resources", "instructional design", "key account management",
      "leadership", "leadership development", "lean manufacturing", "management",
      "management consulting", "management development", "manufacturing", "mbti",
      "new business development", "nonprofits", "organizational culture",
      "organizational design", "organizational development", "organizational effectiveness",
      "organizational learning", "organizational networks", "performance improvement",
      "performance management", "personal development", "product development",
      "public speaking", "sales", "sales management", "sales operations",
      "strategic leadership", "strategic planning", "strategic thinking", "strategy",
      "succession planning", "talent management", "team building", "team facilitation",
      "team leadership", "thought leadership", "training", "training delivery",
      "workshop facilitation"
    ],
    "interests": [
      "arts and culture", "automobiles", "baseball", "civil rights and social action",
      "collecting", "cooking", "diet", "education", "electronics", "environment",
      "exercise", "fitness", "football", "golf", "health", "hockey", "home decoration",
      "home improvement", "human rights", "investing", "joggin", "kids", "medicine",
      "movies", "music", "outdoors", "poverty alleviation", "reading",
      "science and technology", "skiing", "sports", "television", "travel", "traveling",
      "walking", "watching baseball", "watching football", "watching hockey",
      "watching sports", "wine"
    ],
    "personIndustry": "computer software",
    "seniorityLabel": "cxo",
    "jobTenureStart": "2021-05",
    "companyFounded": 2005,
    "companyMetro": "san francisco, california",
    "githubUrl": ""
  },
  {
    "fullName": "lisa watts",
    "firstName": "lisa",
    "lastName": "watts",
    "jobTitle": "chief executive officer",
    "companyName": "cree8",
    "companyWebsite": "cree8.io",
    "companyIndustry": "software development",
    "companySize": "1-10",
    "companyLocation": "los angeles, california, united states",
    "companyLocality": "los angeles",
    "companyRegion": "california",
    "companyCountry": "united states",
    "companyLinkedin": "linkedin.com/company/letscree8",
    "personRegion": true,
    "personCountry": "united states",
    "personLocality": true,
    "twitterUrl": "twitter.com/lisamwatts",
    "twitterHandle": "lisamwatts",
    "facebookUrl": "facebook.com/lisa.watts",
    "linkedinPersonal": "linkedin.com/in/lwatts",
    "linkedinUsername": "lwatts",
    "workEmailAvailable": true,
    "personalEmailAvailable": true,
    "mobilePhoneAvailable": true,
    "seniorityLevels": [
      "cxo"
    ],
    "skills": [
      "advertising", "augmented reality", "board of directors", "business development",
      "business planning", "business strategy", "change management", "creative strategy",
      "cross functional team leadership", "design", "design strategy",
      "digital business development", "e commerce", "entrepreneur", "entrepreneurship",
      "executive production", "go to market strategy", "leadership", "management",
      "management consulting", "marketing", "marketing strategy", "networking",
      "new business development", "new media", "non profits", "nonprofits",
      "operations management", "organizational development", "process improvement",
      "product development", "product management", "product marketing",
      "program management", "project management", "public speaking", "research",
      "retail technology", "sales", "small business", "social impact",
      "stakeholder management", "start ups", "startups", "strategic partnerships",
      "strategic planning", "strategy", "team building", "team leadership", "virtual reality"
    ],
    "interests": [
      "camping", "career", "children", "electronics", "fine art", "gourmet cuisine",
      "home decoration", "home improvement", "jewelry", "kids", "new technology",
      "outdoors", "reading", "sports", "wine"
    ],
    "personIndustry": "computer software",
    "seniorityLabel": "cxo",
    "jobTenureStart": "2023-06",
    "companyFounded": 2023,
    "companyMetro": "los angeles, california",
    "githubUrl": ""
  }
];
